### ISSUE TITLE
Files not compiled

### ISSUE THREAD

**Issue by Ceyar** [Veams/cli#13]
Hello,  I try to make dev:build or dev:prod but I have this error when start compiling files:
`(!) Files not compiled: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined`.

I have only this information, have you any idea of where I have to change something to get it work?

Thank you
Dan

**Comment by Sebastian-Fitzner** [comment]
Hi there,

I think it looks more like an issue related to the static site generator (Mangony). Can you tell me, which version of Mangony you are using? Did you changed anything in the generell setup? When you have updated Mangony to version 2.x then this error can happen, because there are some breaking major changes. 
Can you post your `mangony.config` in here as well as your `veams-cli.json`?

**Comment by Ceyar** [comment]
I didn't change anything in general setup. But this project has already been used before by another collaborator and I have deleted some components. Maybe the problem come from deleting theses components, because when I run prod:build, it compile some components but not all and it does not finish the process.

My mangony version:  **"mangony": "^1.5.0"**

So here are my config files:
**mangony.config.js**
```
'use strict';

const config = require('../../../veams-cli');

module.exports = {
	options: {
		allow: {
			YFMContextData: true,
			YFMLayout: true
		},
		collections: [
			'sitemap',
			'type'
		],
		cwd: config.paths.src,
		dest: config.paths.dest,
		exportData: false,
		flatten: true,
		types: {
			data: {
				dir: '',
				files: [
					'app/core/**/*.hjson',
					'app/core/**/*.json',
					// 'app/features/**/*.hjson',
					// 'app/features/**/*.json',
					'app/shared/components/**/*.hjson',
					'app/shared/components/**/*.json',
					'app/shared/utilities/**/*.hjson',
					'app/shared/utilities/**/*.json'
				]
			},
			partials: {
				dir: '',
				files: [
					'app/shared/components/**/*.hbs',
					'app/core/components/**/*.hbs',
					// 'app/features/**/*.hbs',
					'app/shared/utilities/**/*.hbs'
				]
			},
			pages: {
				dir: '',
				files: [
					'app/pages/**/*.hbs',
					'app/shared/components/**/*.hbs',
					// 'app/features/**/*.hbs',
					'app/shared/utilities/**/*.hbs'
				]
			},
			layouts: {
				dir: '',
				files: [
					'app/core/layouts/**/*.hbs',
					'docs/layouts/**/*.hbs'
				]
			}
		},
		helpers: [
			'app/shared/utilities/template-helpers/*.js'
		]
	},
	dev: {
		options: {
			compileStaticFiles: false,
			devServer: {
				start: true,
				injectScript: false,
				useExt: true,
				port: config.ports.server,
				bsOptions: {
					proxy: 'localhost:' + config.ports.server,
					port: config.ports.app,
					files: [
						config.paths.dest + '/**/*.html',
						config.paths.dest + '/css/**/*.css',
						config.paths.dest + '/scripts/**/*.js'
					]
				}
			},
			watch: true
		}
	},
	dist: {
		options: {
			compileStaticFiles: true,
			watch: false
		}
	}
};
```

and **veams-cli.json**

```
{
    "projectType": "static-page-app",
    "blueprints": {
        "api": {
            "skipImports": true,
            "path": "node_modules/@veams/bp-mock-api"
        }
    },
    "config": {
        "src": "configs/tasks/_grunt/*.js"
    },
    "entries": {
        "style": "src/app/app.scss",
        "script": "src/app/app.js"
    },
    "insertpoints": [
        "src/app/app.js",
        "src/app/core/layouts",
        "src/app/pages",
        "src/app/features",
        "src/app/app.events.js"
    ],
    "paths": {
        "api": "src/server/api",
        "app": "src/app",
        "dest": "app",
        "assets": "src/app/assets",
        "env": "environments",
        "component": "src/app/shared/components",
        "config": "configs",
        "docs": "src/docs",
        "mocks": "src/server/mocks",
        "package": "src/app/shared/components",
        "server": "src/server",
        "src": "src",
        "utility": "src/app/shared/utilities"
    },
    "ports": {
        "app": 3000,
        "server": 2999
    },
    "startPath": "index.html"
}
```

Thank you

**Comment by Sebastian-Fitzner** [comment]
> But this project has already been used before by another collaborator and I have deleted some components. 

This helps alot. To see, which file will not get compiled, there is an option in mangony.config. Just add `debug: true` to the options like so: 

``` js 
module.exports = {
	options: {
		...
		debug: true,
		...
	},
	...
};
```

This shows you which file mangony starts to compile and cannot finish! In that file which does not get compiled you should take a look and delete alle unecessary refererences. `{{debug}}` is your friend if you want to find some hints in that file... 
You can also start the project (`npm run start`), navigate to the route which cannot be compiled and debug while reloading is enabled...

**Comment by Ceyar** [comment]
I'll give a try and give you feedback.

Thank you so much for taking time.

**Comment by Ceyar** [comment]
Ok I solved the problem using "debug: true".

I was looping a component and passing variables in it, but inside of each component I missed to make an `if` statement to check if the variable was passed or not. This made me an error, that's funny because when I ran `npm run start`, I didn't get any errors.

So thank you for your debug tips  so helpful. I'll certainly come with another issues (maybe stupid -_-) in the next  5 minutes.

So thank's a lot for your time and knowledge

**Comment by Sebastian-Fitzner** [comment]
> that's funny because when I ran npm run start, I didn't get any errors.

Nah, in development mode (`npm run start`) you need to go the page to see the error on a server rendered. Mangony is only rendering the route you navigate to, so it does not check any other routes.

**Comment by Ceyar** [comment]
Ok I understand.

Thank you and best regards
