### ISSUE TITLE
Importing global script the right way

### ISSUE THREAD

**Issue by Ceyar** [Veams/cli#14]
Hi Sebastian, I have a question about importing some scripts files to use them globally.
In which file is the smartest way to import them? Have you some advices?

Thank you

**Comment by Sebastian-Fitzner** [comment]
What do you mean with global script. You want to add something to `window`? If so, `app.veams` is a good place to start ...

**Comment by Ceyar** [comment]
Yes scripts like polyfill for example.

Ok I'll try this.

Thank you
