### ISSUE TITLE
Settings of generated component should contain reference to scss file and js file

### ISSUE THREAD

**Issue by andy-gutsche** [Veams/cli#2]
**Steps to reproduce**
- Generate a new component `my-component` with with or without Javascript

**Expected result**
- `my-component.settings.json` should contain `scssFiles`-Array and `jsFiles`-Array (if JavaScript was chosen)

**Current result**
- `scssFiles`-Array and `jsFiles`-Array are missing, therefore these files have no source code output on their corresponding documentation page

**Comment by Sebastian-Fitzner** [comment]
Fixed in latest `@veams/generator-veams` version (v1.0.0-rc11)
