### ISSUE TITLE
New generated components style importing occurs backslash problem on windows 10.

### ISSUE THREAD

**Issue by natrenakres** [Veams/cli#3]
Hi,

We have faced the backslash problem in windows 10 after generate new component. Veams added the new component style file path as @import statement to app.scss file but file path has backslash in windows 10.

**Steps to reproduce:** veams -g c sample-component

**Expected Result:**  The Component style file should add to app.scss file correctly and sass-loader should find the path of style.

**Actual result:**
`@import "shared\components\sample-component\styles/sample-component";`

**Hint:**
Loader: Webpack

@veams/generator-veams: 1.0.0-rc17
@veams/cli: 1.0.0-rc9
inserter: 1.1.3

OS: Windows 10

**Comment by Sebastian-Fitzner** [comment]
Fix is implemented in v1.0.0-rc11. Can you check against this version? Thx ...
